"""UNSW-NB15 loading, with the same guarantees as the CIC-IDS2017 loader.

The two datasets are kept separate rather than merged into a shared taxonomy.
They were generated by different procedures on different networks, and their
attack categories do not correspond one-to-one, so mapping one onto the other
would assert an equivalence the data does not support.

UNSW-NB15 matters here for a reason beyond breadth: it carries ten classes
against CIC-IDS2017's five. Under a 5-way protocol that means episodes draw a
different subset of classes each time, so class selection is no longer
degenerate and classes genuinely unseen during meta-training can be held out at
meta-test time -- the scenario the few-shot framing is about, and the one the
CIC-IDS2017 copy cannot test.
"""

from __future__ import annotations

import logging
from dataclasses import asdict
from pathlib import Path

import numpy as np

from .data import (
    DatasetBundle,
    SplitSpec,
    _assert_disjoint,
    _cache_path,
    _load_cached,
    _read_csvs,
    _save_cached,
    deduplicate_indices,
)

log = logging.getLogger(__name__)

# The published files spell the categories inconsistently between the training
# and testing CSVs ("Backdoor" and "Backdoors" both occur).
UNSW_LABEL_MAP: dict[str, str] = {
    "NORMAL": "Normal",
    "GENERIC": "Generic",
    "EXPLOITS": "Exploits",
    "FUZZERS": "Fuzzers",
    "DOS": "DoS",
    "RECONNAISSANCE": "Reconnaissance",
    "ANALYSIS": "Analysis",
    "BACKDOOR": "Backdoor",
    "BACKDOORS": "Backdoor",
    "SHELLCODE": "Shellcode",
    "WORMS": "Worms",
}

UNSW_CLASSES = (
    "Normal", "Generic", "Exploits", "Fuzzers", "DoS",
    "Reconnaissance", "Analysis", "Backdoor", "Shellcode", "Worms",
)

# Identifiers, endpoint addresses and the binary label, which would leak the
# target directly.
UNSW_DROP_COLUMNS = (
    "id", "label", "attack_cat", "srcip", "dstip", "sport", "dsport",
    "Stime", "Ltime", "stime", "ltime",
)

# Genuinely categorical behavioural features. Unlike CIC-IDS2017, these carry
# signal and are one-hot encoded rather than discarded.
UNSW_CATEGORICAL = ("proto", "service", "state")


def load_unsw_nb15(
    path: str | Path,
    classes: tuple[str, ...] = UNSW_CLASSES,
    split: SplitSpec | None = None,
    seed: int = 0,
    max_per_class: int | None = 60_000,
    clip_quantile: float = 0.999,
    drop_constant: bool = True,
    dedup_decimals: int | None = None,
    cache_dir: str | Path | None = None,
    max_categories: int = 32,
) -> DatasetBundle:
    """Load UNSW-NB15 and return instance-disjoint meta-splits.

    Accepts the published training and testing CSVs -- a directory containing
    both is read and concatenated, since this pipeline makes its own splits --
    or a single consolidated file.

    Categorical columns are one-hot encoded against the categories present in
    the *training pool only*. A category first seen in validation or test maps
    to the all-zero pattern, which is the honest encoding of "not seen during
    training" and keeps the test distribution out of the feature definition.
    """
    split = split or SplitSpec()
    path = Path(path)
    rng = np.random.default_rng(seed)

    cached = _cache_path(cache_dir, path, classes, split, seed, max_per_class,
                         clip_quantile, drop_constant, dedup_decimals)
    if cached is not None and cached.exists():
        try:
            bundle = _load_cached(cached)
            log.info("loaded UNSW-NB15 from cache (%s)", cached.name)
            return bundle
        except (OSError, KeyError, ValueError) as exc:
            log.warning("cache at %s unusable (%s); rebuilding", cached, exc)

    df = _read_csvs(path)
    if "attack_cat" not in df.columns:
        raise ValueError(
            "UNSW-NB15 needs an 'attack_cat' column for multi-class episodes; "
            f"found {list(df.columns)[:25]}. The binary-label-only variant of "
            "this dataset cannot support an N-way protocol."
        )
    raw_n = len(df)

    # Benign rows carry an empty attack_cat in the published files.
    canonical = (df["attack_cat"].fillna("Normal").replace("", "Normal")
                 .map(lambda v: " ".join(str(v).strip().upper().split())))
    unknown = sorted(set(canonical) - set(UNSW_LABEL_MAP))
    if unknown:
        log.warning("dropping %d rows with unmapped attack_cat: %s",
                    int(canonical.isin(unknown).sum()), unknown)
    df = df.assign(_class=canonical.map(UNSW_LABEL_MAP))
    df = df[df["_class"].notna() & df["_class"].isin(classes)]
    if df.empty:
        raise ValueError(f"no rows remain after filtering to {list(classes)}")

    class_names = [c for c in classes if (df["_class"] == c).any()]
    absent = [c for c in classes if c not in class_names]
    if absent:
        log.info("classes absent from this file: %s", absent)
    class_to_id = {name: i for i, name in enumerate(class_names)}
    y_all = df["_class"].map(class_to_id).to_numpy(dtype=np.int64)

    dropped = [c for c in UNSW_DROP_COLUMNS if c in df.columns] + ["_class"]
    features = df.drop(columns=dropped, errors="ignore")
    categorical = [c for c in UNSW_CATEGORICAL if c in features.columns]

    numeric = features.drop(columns=categorical)
    leftover = numeric.select_dtypes(exclude=[np.number]).columns.tolist()
    if leftover:
        log.info("dropping %d unusable non-numeric columns: %s",
                 len(leftover), leftover)
        numeric = numeric.drop(columns=leftover)

    X_numeric = numeric.to_numpy(dtype=np.float64, copy=True)
    X_numeric[~np.isfinite(X_numeric)] = np.nan
    numeric_names = numeric.columns.tolist()

    # --- optional deduplication, before any split --------------------------
    dedup_stats = None
    keep_rows = np.arange(len(y_all))
    if dedup_decimals is not None:
        before = len(keep_rows)
        keep_rows = deduplicate_indices(X_numeric, decimals=dedup_decimals)
        dedup_stats = {
            "decimals": dedup_decimals,
            "rows_before": int(before),
            "rows_after": int(len(keep_rows)),
            "removed_fraction": float(1 - len(keep_rows) / before),
            "removed_per_class": {
                class_names[c]: int((y_all == c).sum() - (y_all[keep_rows] == c).sum())
                for c in range(len(class_names))
            },
        }
        log.info("deduplication at %d decimals: %d -> %d flows (%.1f%% removed)",
                 dedup_decimals, before, len(keep_rows),
                 100 * dedup_stats["removed_fraction"])
        X_numeric, y_all = X_numeric[keep_rows], y_all[keep_rows]
        features = features.iloc[keep_rows]

    # --- stratified, instance-level split, before fitting anything ---------
    idx_train, idx_val, idx_test = [], [], []
    for cid in range(len(class_names)):
        idx = np.flatnonzero(y_all == cid)
        rng.shuffle(idx)
        if max_per_class is not None and len(idx) > max_per_class:
            idx = idx[:max_per_class]
        n_tr = int(round(len(idx) * split.train))
        n_va = int(round(len(idx) * split.val))
        idx_train.append(idx[:n_tr])
        idx_val.append(idx[n_tr:n_tr + n_va])
        idx_test.append(idx[n_tr + n_va:])
    idx_train = np.concatenate(idx_train)
    idx_val = np.concatenate(idx_val)
    idx_test = np.concatenate(idx_test)
    _assert_disjoint(idx_train, idx_val, idx_test)

    # --- one-hot encoding fitted on the training pool only -----------------
    blocks, block_names = [], []
    for column in categorical:
        values = features[column].astype(str).str.strip().str.lower().to_numpy()
        train_values, counts = np.unique(values[idx_train], return_counts=True)
        keep = list(train_values[np.argsort(-counts)][:max_categories])
        lookup = {v: i for i, v in enumerate(keep)}
        block = np.zeros((len(values), len(keep)), dtype=np.float64)
        for row, value in enumerate(values):
            position = lookup.get(value)
            if position is not None:
                block[row, position] = 1.0
        blocks.append(block)
        block_names += [f"{column}={v}" for v in keep]
        log.info("one-hot %s: kept %d of %d categories seen in training",
                 column, len(keep), len(train_values))

    X_all = np.hstack([X_numeric] + blocks) if blocks else X_numeric
    feature_names = numeric_names + block_names

    # --- preprocessing fitted on the training pool only --------------------
    medians = np.nanmedian(X_all[idx_train], axis=0)
    medians = np.where(np.isfinite(medians), medians, 0.0)

    def impute(X: np.ndarray) -> np.ndarray:
        out = X.copy()
        bad = ~np.isfinite(out)
        if bad.any():
            out[bad] = np.take(medians, np.nonzero(bad)[1])
        return out

    train_imputed = impute(X_all[idx_train])
    lo = np.quantile(train_imputed, 1.0 - clip_quantile, axis=0)
    hi = np.quantile(train_imputed, clip_quantile, axis=0)
    prepare = lambda X: np.clip(impute(X), lo, hi)

    Xtr = prepare(X_all[idx_train])
    Xva = prepare(X_all[idx_val])
    Xte = prepare(X_all[idx_test])

    mean, std = Xtr.mean(axis=0), Xtr.std(axis=0)
    if drop_constant:
        keep_feature = std > 1e-8
        if not keep_feature.all():
            log.info("dropping %d zero-variance features", int((~keep_feature).sum()))
            Xtr, Xva, Xte = Xtr[:, keep_feature], Xva[:, keep_feature], Xte[:, keep_feature]
            mean, std = mean[keep_feature], std[keep_feature]
            feature_names = [f for f, k in zip(feature_names, keep_feature) if k]
    std = np.where(std > 1e-8, std, 1.0)
    scale = lambda X: ((X - mean) / std).astype(np.float32)

    ytr, yva, yte = y_all[idx_train], y_all[idx_val], y_all[idx_test]
    bundle = DatasetBundle(
        X_train=scale(Xtr), y_train=ytr,
        X_val=scale(Xva), y_val=yva,
        X_test=scale(Xte), y_test=yte,
        class_names=class_names,
        feature_names=feature_names,
        meta={
            "dataset": "UNSW-NB15",
            "source": str(path),
            "rows_read": int(raw_n),
            "rows_retained": int(len(ytr) + len(yva) + len(yte)),
            "seed": seed,
            "split": asdict(split),
            "max_per_class": max_per_class,
            "clip_quantile": clip_quantile,
            "n_features": len(feature_names),
            "class_names": class_names,
            "categorical": categorical,
            "deduplication": dedup_stats,
            "counts": {
                name: {
                    class_names[i]: int((y == i).sum())
                    for i in range(len(class_names))
                }
                for name, y in (("train", ytr), ("val", yva), ("test", yte))
            },
        },
    )
    log.info("loaded UNSW-NB15: %d train / %d val / %d test flows, "
             "%d features, %d classes",
             len(ytr), len(yva), len(yte), bundle.n_features, len(class_names))
    if cached is not None:
        _save_cached(bundle, cached)
    return bundle
